# Generated by Django 4.0.2 on 2022-02-05 05:15

from django.db import migrations, models
import django.db.models.deletion
import webapp.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(max_length=200, validators=[webapp.validators.MinLengthValidator(7)], verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
            ],
            options={
                'verbose_name': 'poll',
                'verbose_name_plural': 'polls',
                'db_table': 'Polls',
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200, validators=[webapp.validators.MinLengthValidator(10)], verbose_name='Description')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='webapp.poll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'choice',
                'verbose_name_plural': 'choices',
                'db_table': 'Choices',
            },
        ),
    ]
