# Generated by Django 4.0.2 on 2022-02-05 05:23

from django.db import migrations, models
import webapp.validators


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(max_length=200, validators=[webapp.validators.MinLengthValidator(10)], verbose_name="Choice's text"),
        ),
        migrations.AlterField(
            model_name='poll',
            name='question',
            field=models.TextField(max_length=200, validators=[webapp.validators.MinLengthValidator(7)], verbose_name='Question'),
        ),
    ]
