# Generated by Django 4.0.2 on 2022-02-05 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_choice_text_alter_poll_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date created')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='webapp.choice', verbose_name='Choice')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='polls', to='webapp.poll', verbose_name='Poll')),
            ],
            options={
                'verbose_name': 'answer',
                'verbose_name_plural': 'answers',
                'db_table': 'Answers',
            },
        ),
    ]
